apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::066175511719:role/eksctl-eksworkshop-eksctl-nodegro-NodeInstanceRole-E8TD37F70QEK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::066175511719:role/codebuild-hol-eatgo-builder-service-role
      username: codebuild-hol-eatgo-builder-service-role
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-21T07:21:18Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1387"
  uid: 3fec1fe6-64c7-431c-9c6f-617cd4ff220f
